#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2012 Ethan Zhang<http://github.com/Ethan-Zhang> 
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


import os
import sys
import shutil
import re
import optparse

def main():

    parser = optparse.OptionParser()
    parser.add_option("-n", "--project_name",
                      dest="project_name",
                        help="project name")
    parser.add_option("-d", "--dst_path",
                      dest="dst_path",
                        help="path to install")
    parser.add_option("-l", "--license_file",
                    dest="license_file",
                    help="license header file path")
    options, args = parser.parse_args()

    if not options.project_name:
        parser.error('Must provide --project_name')
    if not options.dst_path:
        if args:
            options.dst_path = os.path.abspath(args[0])
        else:
            options.dst_path = os.path.abspath('.')
    if options.license_file:
        options.license_file = os.path.abspath(options.license_file)
        if not os.path.isfile(options.license_file):
            options.license_file = None

    project_name = options.project_name

    possible_topdir = os.path.normpath(os.path.join(os.path.abspath(sys.argv[0]),
                                   os.pardir,
                                    os.pardir))
    if os.path.exists(os.path.join(possible_topdir, 'mownfish', '__init__.py')):
        src_path = possible_topdir
    else:
        print('mownfish project Error')
        sys.exit(0)
    dst_path = options.dst_path
    
    try:
        os.mkdir(os.path.join(dst_path,project_name))
        os.mkdir(os.path.join(dst_path,project_name,'log'))
    except OSError as e:
        print(e)
        sys.exit(0)
    

    shutil.copytree(os.path.join(src_path,'etc'),
                os.path.join(dst_path,project_name,'etc'))
    shutil.copytree(os.path.join(src_path,'mownfish'),
            os.path.join(dst_path,project_name,project_name))
    shutil.copy(os.path.join(src_path, 'setup.py'),
            os.path.join(dst_path, project_name))

    for root, dirs, files in os.walk(dst_path):
        for name in files:
            if name.find('mownfish') != -1:
                old_name = name
                name = name.replace('mownfish', project_name)
                os.rename(os.path.join(root, old_name), 
                        os.path.join(root, name))

            if re.match(r'.+py$|'+project_name, name):
                with open(os.path.join(root,name),"r+") as f:
                    d = f.read()
                    d = d.replace('mownfish', project_name)
                    if options.license_file:
                        with open(options.license_file, "r") as fl:
                            licenses = fl.read()
                            d = licenses+d[d.find('# under the License.')+20:]
                    f.truncate(0)
                    f.seek(0,0)
                    f.write(d)

if __name__ == '__main__':
    main()
